site_name: MkDocs Sequence Plugin
markdown_extensions:
  - codehilite
theme:
  name: 'material'
plugins:
  - search
  - sequence-js:
      theme: simple
      popup: true

nav:
    - 'Plugin': 'index.md'
    - 'Dependencies': 'dependencies.md'
    
site_url: https://fcannizzaro.github.io/mkdocs-sequence-js-plugin/
